name: Deploy na AWS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar ambiente AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Instalar o Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Inicializar o Terraform
        run: |
          cd infra
          terraform init

      - name: Fazer o deploy da aplicação
        run: |
          cd infra
          terraform init
          terraform apply -auto-approve